version: 4
shared:
  environment:
    PACKAGE_DIRECTORY: src/pypirun
    
jobs:
  validate_test:
    template: python/validate_unittest
    requires: [~commit, ~pr]

  validate_lint:
    template: python/validate_lint
    requires: [~commit, ~pr]

  validate_codestyle:
    template: python/validate_codestyle
    requires: [~commit, ~pr]

  validate_safetydb:
    template: python/validate_safety
    requires: [~commit, ~pr]
    
  validate_security:
    template: python/validate_security
    requires: [~commit, ~pr]
  
  validate_sd_cmd:
    image: node:8
    steps:
      - validate: sd-cmd validate -f sd-cmd/sd-command.yaml
    requires: [~commit, ~pr]

  generate_version:
    template: python/generate_version
    requires: [~commit]
  
  publish_test_pypi:
    template: python/package_python
    environment:
      PUBLISH: True
      TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
    requires: [validate_test, validate_lint, validate_codestyle, validate_safetydb, validate_security,  generate_version]

  verify_test_package:
    template: python/validate_pypi_package
    environment:
        PYPI_INDEX_URL: https://test.pypi.org/simple
    requires: [publish_test_pypi]

  publish_pypi:
    template: python/package_python
    environment:
      PUBLISH: True
    requires: [verify_test_package]

  publish_sd_cmd:
    image: node:8
    steps:
      - publish: sd-cmd publish -f sd-cmd/sd-command.yaml
    requires: [validate_sd_cmd, validate_test, validate_lint, validate_codestyle, validate_safetydb, validate_security,  generate_version]

  test_sd_cmd_alpine:
    image: alpine:latest
    steps:
      - testpypirun: sd-cmd python/pypirun@latest serviceping serviceping -c 1 yahoo.com
    requires: [publish_sd_cmd]

  test_sd_cmd_fedora:
    image: fedora:latest
    steps:
      - install_dependencies: yum install -y findutils
      - testpypirun: sd-cmd python/pypirun@latest serviceping serviceping -c 1 yahoo.com
    requires: [publish_sd_cmd]

  test_sd_cmd_node:
    image: node:8
    steps:
      - testpypirun: sd-cmd python/pypirun@latest serviceping serviceping -c 1 yahoo.com
    requires: [publish_sd_cmd]

  test_sd_cmd_ubuntu:
    image: ubuntu:19.04
    steps:
      - testpypirun: sd-cmd python/pypirun@latest serviceping serviceping -c 1 yahoo.com
    requires: [publish_sd_cmd]

  promote_sd_cmd:
    image: alpine:latest
    steps:
      - promote: sd-cmd promote python/pypirun latest stable
    requires: [test_sd_cmd_alpine, test_sd_cmd_fedora, test_sd_cmd_ubuntu]
